# Generated by Django 3.2.12 on 2022-03-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xlapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xls',
            name='API_WELL_NUMBER',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='xls',
            name='BRINE',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='xls',
            name='GAS',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='xls',
            name='OIL',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='xls',
            name='QUARTER',
            field=models.IntegerField(null=True),
        ),
    ]
