# Generated by Django 3.2.12 on 2022-03-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xlapp', '0002_auto_20220301_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xlss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('API_WELL_NUMBER', models.IntegerField(null=True)),
                ('QUARTER', models.IntegerField(null=True)),
                ('OIL', models.IntegerField(null=True)),
                ('GAS', models.IntegerField(null=True)),
                ('BRINE', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'Xlss',
            },
        ),
        migrations.DeleteModel(
            name='Xls',
        ),
    ]
