# Generated by Django 3.2.12 on 2022-03-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xlapp', '0003_auto_20220301_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('API_WELL_NUMBER', models.IntegerField(null=True)),
                ('OIL', models.IntegerField(null=True)),
                ('GAS', models.IntegerField(null=True)),
                ('BRINE', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'Sum',
            },
        ),
    ]
